---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: master[0]
  roles:
    - role: traefik
      when: deploy_traefik = true | default(false)

- hosts: master[0]
  roles:
    - role: rancher
      when: deploy_rancher = true | default(false)
