---
k3s_version: v1.23.4+k3s1
ansible_user: serveradmin
systemd_dir: /etc/systemd/system

# set your timezone
system_timezone: "Your/Timezone"

# interface which will be used for flannel
# debian is usually eth0, ubuntu could be either that or ens18, varies by OS. check with `ip -a` in terminal
flannel_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "192.168.10.15"

# k3s_token is required  masters can talk together securely
k3s_token: "SOME-SUPER-SECRET-TOKEN"

# change these to your liking, the only required ones are --no-deploy servicelb and --no-depoly traefik (this playbook deploys traefik)
# -----------------------
# 7-24-2022: added additional args for prometheus monitoring following Tim's tutorial on that, If you don't plan to do monitoring they can be removed
# "--kube-controller-manager-arg bind-address=0.0.0.0 --kube-proxy-arg metrics-bind-address=0.0.0.0 --kube-scheduler-arg bind-address=0.0.0.0 --etcd-expose-metrics true --kubelet-arg containerd=/run/k3s/containerd/containerd.sock"
extra_server_args: "--no-deploy servicelb --no-deploy traefik --write-kubeconfig-mode 644 --kube-controller-manager-arg bind-address=0.0.0.0 --kube-proxy-arg metrics-bind-address=0.0.0.0 --kube-scheduler-arg bind-address=0.0.0.0 --etcd-expose-metrics true --kubelet-arg containerd=/run/k3s/containerd/containerd.sock"
extra_agent_args: ""

# image tag for kube-vip
kube_vip_tag_version: "v0.4.4"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.12.1"
metal_lb_controller_tag_version: "v0.12.1"

# metallb ip range for load balancer
metal_lb_ip_range: "192.168.10.40-192.168.10.50"

#first IP from above metalLB range which will be used by traefik
#--IMPORTANT-- This IP NEEDS to be contained in the above pool provided to metalLB.  Usually I use the first one in that range
traefik_endpoint_ip: "192.168.10.40"

#set this in your local DNS server (ie. Pihole, or pfsense, etc.) pointing to the IP from the line just above.
traefik_dash_dns_name: "traefik.yourdomain.lan"

#number of traefik pods you want running
traefik_replicas: 1

#number of replicas you want for rancher's pods
rancher_replicas: 3

#rancher dns name
rancher_dns_name: "rancher.yourdomain.lan"

#version of cert-manager to deploy
cert_manager_ver: "v1.7.1"

# If Vagrant is used
# ansible_user: vagrant
# flannel_iface: "eth1"
# extra_server_args: "--node-ip={{ ansible_eth1.ipv4.address }} --flannel-iface={{ flannel_iface }} --no-deploy servicelb --no-deploy traefik"
# extra_agent_args: "--flannel-iface={{ flannel_iface }}"
